### ISSUE TITLE
Are the JOSE registrations missing "Key Type: OKP"?

### ISSUE THREAD

**Issue by quartzjer** [tplooker/draft-looker-bls-jose-cose#11]
It's in each of the COSE registrations, should it be in the JOSE ones too?

**Comment by tplooker** [comment]
If by registration you mean the IANA section for each then the reason they key type is absent in the JOSE registrations is that it is not required for that IANA registry [see here](https://www.iana.org/assignments/jose/jose.xhtml#web-key-elliptic-curve), whereas with COSE the key type forms part of the registration [see here](https://www.iana.org/assignments/cose/cose.xhtml#elliptic-curves)

**Comment by selfissued** [comment]
@tplooker's analysis of the issue is correct.
