### ISSUE TITLE
Relation to existing draft?

### ISSUE THREAD

**Issue by quartzjer** [tplooker/draft-looker-bls-jose-cose#3]
I'm assuming this is a successor to https://datatracker.ietf.org/doc/html/draft-denhartog-pairing-curves-jose-cose-00#section-3.1 but only specifically for the BLS curve?

**Comment by tplooker** [comment]
Yes you are correct, thanks for raising, hope to make it more clear with links to drafts etc.

**Comment by tplooker** [comment]
This old repository is now archived and pointing at this draft
