### ISSUE TITLE
References needed for some cited related work

### ISSUE THREAD

**Issue by selfissued** [tplooker/draft-looker-bls-jose-cose#5]
The draft includes "Further work on a similar scheme has also been progressed at the FIDO Alliance and W3C. Similarly Intel released (EPID) which provides a solution to remote hardware attestation for Intel Software Guard Extension (SGX) enabled environments."  IETF style guidelines say that if we're citing work, we should provide references to it.

**Comment by tplooker** [comment]
Addressed in #6
