### ISSUE TITLE
Rename draft to conform to IETF naming conventions

### ISSUE THREAD

**Issue by selfissued** [tplooker/draft-looker-bls-jose-cose#9]
To submit to the COSE working group, the draft name must be of the form `draft-<lastname>-cose-<draftname>`.  I'd suggest the identifier `draft-looker-cose-bls-curves-representations` or something similar.

Note that both the filename and the draft name in the markdown (which is currently `draft-looker-bls-jose-cose-00`) need to be changed.

**Comment by tplooker** [comment]
Fixed in ed6cd3ad47070a4a6e793717837272e404710ef2
